# NUMPY

In [1]:
import numpy as np

### Creating an array

In [4]:
my_list=[1,2,3]
x=np.array(my_list)
x

array([1, 2, 3])

In [5]:
y=np.array([4,5,6])

In [6]:
y

array([4, 5, 6])

In [9]:
m=np.array([[7,8,9],[10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

#### shape of array

In [12]:
m.shape

(2, 3)

#### Generating an arrray using np.arange

we define range and step size

In [14]:
n=np.arange(0,30,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [15]:
n.shape

(15,)

####  Reshaping a function

In [115]:
# Reshape function need assignemnt to another varaible array where as resize works on array itself
n=n.reshape(3,5)
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

### lin space function is used to divide a given range in given number of arraylist

In [22]:
o=np.linspace(0,4,9)
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

#### Resize  to change the dimension in place

In [24]:
o.resize(3,3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

### Ones :  Array of 1

In [29]:
#Method #1  : square brackets inside
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
#Method #2  : round brackets inside
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### Zero: Array of 0s

In [32]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### eye: Identity matrix

In [35]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### diag: diagnol array (converts the 1d arrray elements to a daignol array) 

In [38]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

### Array with repeated list

In [41]:
# using multiplication
np.array([1,2,3]*3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

### using  numpy Repeated list

In [42]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Combining arrray to create a new one

In [43]:
p=np.ones([2,3],int)

In [44]:
p

array([[1, 1, 1],
       [1, 1, 1]])

## Vertical stacking

In [45]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

## Horizontal Stacking

In [47]:
np.hstack([p,2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations on Numpy array

In [48]:
x+y

array([5, 7, 9])

In [49]:
x*y

array([ 4, 10, 18])

In [50]:
x

array([1, 2, 3])

In [51]:
y

array([4, 5, 6])

In [52]:
x**2

array([1, 4, 9], dtype=int32)

In [53]:
x.dot(y)

32

In [54]:
#  Array that generates 
x=np.array([y,y**2])

In [55]:
x

array([[ 4,  5,  6],
       [16, 25, 36]])

In [57]:
x.shape

(2, 3)

## Transpose of an Array

In [58]:
x.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [59]:
x.T.shape

(3, 2)

## dtype: to know the type of an array

In [60]:
x.dtype

dtype('int32')

##  Type casting an array using : astype

In [63]:
x=x.astype('f')
x.dtype

dtype('float32')

## Numpy Math functions

In [64]:
a=np.array([-4,-2,1,3,5])

In [65]:
a.sum()

3

In [66]:
a.max()

5

In [67]:
a.min()

-4

In [68]:
a.mean()

0.6

In [69]:
a.std()

3.2619012860600183

## To find the index of a maximum and Minimum Value

In [70]:
a.argmax()

4

In [71]:
a.argmin()

0

## Indexing and Slicing

### Generating an Array with values square

In [85]:
s=np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

### Slicing an Array

In [76]:
s[0],s[4],s[0:3]

(0, 16, array([0, 1, 4], dtype=int32))

####  Slicing an array from  1st to 4th value

In [77]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

#### Slicing an array from last 4 values

In [78]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

In [86]:
#### slicing an array in reverse from last five values to 0 with a difference of 2 values

In [80]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

In [87]:
#REVERSE

k=[1,2,3,4,5]

k[::-1]

[5, 4, 3, 2, 1]

In [116]:
# creating a 6 by 6 dimensional array
r=np.arange(36)
r.resize([6,6])
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [114]:
# Reshape function need assignemnt to another varaible array where as resize works on array itself

g=np.arange(36)
h=g.reshape([6,6])
h

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

#### Picking a value from location [2nd row and 2nd column] from an array 

In [118]:
r[2,2]

14

### Slicing an array : last 3 values of 3rd row  

In [121]:
r[3,3:6]

array([21, 22, 23])

### Slicing an array: 1st two row without last column values

In [122]:
r[:2,:-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

### Slicing an array: selecting every secnd element from the last row

In [123]:
r[-1,::2]

array([30, 32, 34])

### Conditional Indexing and Assigment : using bracket operator

In [125]:
r[r>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

### b Assignment

In [147]:
r2=r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [148]:
r2[:]=0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [149]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

## this looks Dangerous changing r2 causes the  orignal array 'r' to zero the elements coresponding to r2

# TO avoid this we use .copy function

In [150]:
r_copy=r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [151]:
r_copy[:]=10

In [154]:
print(r_copy)
# r copy values updated

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [155]:
print(r)
# orignal arrar r remains same

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


## Iterate Over arrays

In [156]:
test=np.random.randint(0,9,[4,3])

In [157]:
test

array([[2, 5, 4],
       [4, 5, 6],
       [6, 0, 4],
       [1, 3, 4]])

#### Iterating by row

In [159]:
for row in test:
    print(row)

[2 5 4]
[4 5 6]
[6 0 4]
[1 3 4]


#### Iterating by Row index: by using the length indexon array 'test'

In [161]:
for i in range(len(test)):
    print(test[i])

[2 5 4]
[4 5 6]
[6 0 4]
[1 3 4]


### Combining two  ways of iterating by using the enumerate

In [164]:
for i, row in enumerate(test):
    print('row', i ,'is', row)

row 0 is [2 5 4]
row 1 is [4 5 6]
row 2 is [6 0 4]
row 3 is [1 3 4]


In [167]:
# new arraye test 2
test2=test**2
test2

array([[ 4, 25, 16],
       [16, 25, 36],
       [36,  0, 16],
       [ 1,  9, 16]], dtype=int32)

### Zip:To Iterate over both array

In [168]:
for i,j in zip(test,test2):
    print(i,'+',j,'=',i+j)

[2 5 4] + [ 4 25 16] = [ 6 30 20]
[4 5 6] + [16 25 36] = [20 30 42]
[6 0 4] + [36  0 16] = [42  0 20]
[1 3 4] + [ 1  9 16] = [ 2 12 20]
